checklisthq/checklisthq/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login$', 'django.contrib.auth.views.login'),
    url(r'^users/new$', 'main.views.new_user', name='new_user'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^settings$', 'django.contrib.auth.views.password_change'),
    url(r'^done$', 'django.contrib.auth.views.password_change_done'),
    url(r'^user/(?P<username>[a-zA-Z0-9_\.@\+\-]+)$',
        'main.views.checklist_list', name="checklist_list"),
    url(r'^browse$', 'main.views.browse'),
    url(r'^search$', 'main.views.search'),
    url(r'^checklist/new$', 'main.views.new_checklist', name='new_checklist'),
    url(r'^checklist/(?P<id>[0-9]+)$', 'main.views.view_checklist',
        name='view_checklist'),
    url(r'^checklist/(?P<id>[0-9]+)/comments$',
        'main.views.checklist_comments', name='checklist_comments'),
    url(r'^checklist/(?P<id>[0-9]+)/edit$', 'main.views.edit_checklist',
        name='edit_checklist'),
    url(r'^checklist/(?P<id>[0-9]+)/clone$', 'main.views.clone_checklist',
        name='clone_checklist'),
    url(r'^checklist/(?P<id>[0-9]+)/delete$', 'main.views.delete_checklist',
        name='delete_checklist'),
    url(r'^checklist/(?P<id>[0-9]+)/print$', 'main.views.print_checklist',
        name='print_checklist'),
    url(r'^preview$', 'main.views.preview_checklist', name='preview'),
    (r'^comments/', include('django.contrib.comments.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),

    url(r'^.*$', 'main.views.home', name='home'),
)

checklisthq/main/models.py
import unittest

from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

class Checklist(models.Model):
    title = models.CharField(max_length=512)
    owner = models.ForeignKey(User)
    description = models.TextField(default="")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True, auto_now_add=True)
    deleted = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.title

class TestChecklist(unittest.TestCase):
    """
    Ensures the Checklist class works as expected.
    """

    def test_unicode(self):
        """
        The checklist's title is always returned.
        """
        u = User(username='user1', password='password')
        cl = Checklist(title='foo', owner=u, content='bar')
        self.assertEqual(u'foo', cl.__unicode__())

checklisthq/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea

from models import Checklist

class ChecklistForm(forms.ModelForm):
    """
    A form for entering the specification of a checklist.
    """
    class Meta:
        model = Checklist
        fields = ('title', 'description', 'content', 'tags')
        widgets = {
            'description': Textarea(attrs={'rows': 2, 'style': 'width:100%;',
                'class': 'input-xlarge'}),
            'content': Textarea(attrs={'rows': 16, 'style': 'width:100%;',
                'class': 'input-xlarge'}),
        }

class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        label='Your email address'
    )

checklisthq/main/views.py
import logging

from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse

from checklistdsl import lex, parse

from forms import ChecklistForm, NewUserForm
from models import Checklist

_logger = logging.getLogger(__name__)

def home(request):
    """
    Simplest possible case.
    """
    if request.user.is_authenticated():
        return HttpResponseRedirect('/user/%s' % request.user.username)
    else:
        return render(request, 'frontpage.html')

def new_user(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            user = User.objects.create_user(username, email, password)
            u = authenticate(username=username, password=password)
            login(request, u)
            return HttpResponseRedirect('/user/%s' % username)
    else:
        form = NewUserForm()
    context = {}
    context['form'] = form
    return render(request, 'registration/new_user.html', context)

def browse(request):
    context = {}
    checklists = Checklist.objects.all
    context['checklists'] = checklists
    return render(request, 'checklist_browse.html', context)

def checklist_list(request, username):
    context = {}
    try:
        owner = User.objects.get(username=username)
    except User.DoesNotExist:
        # TODO: Return a 404 when we've configured it.
        return HttpResponseRedirect('/')
    checklists = Checklist.objects.filter(owner=owner).order_by('-modified')
    context['checklists'] = checklists
    context['is_own_checklists'] = owner == request.user
    context['owner'] = owner
    return render(request, 'user/checklist_list.html', context)

def new_checklist(request):
    """
    Creates a new checklist.
    """
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    form = ChecklistForm()
    context = {}
    context['action'] = '/checklist/new'
    if request.method == 'POST':
        form = ChecklistForm(request.POST)
        if form.is_valid():
            tags = form.cleaned_data['tags']
            checklist = form.save(commit=False)
            checklist.owner = request.user
            checklist.save()
            checklist.tags.add(*tags)
            context['action'] = '/checklist/%s/edit' % checklist.id
            messages.add_message(request, messages.INFO, "Your changes have been saved...")
            return HttpResponseRedirect(reverse('view_checklist', args=[checklist.id]))

    context['form'] = form
    return render(request, 'user/edit_checklist.html', context)

def view_checklist(request, id):
    checklist = Checklist.objects.get(id=id)
    tokens = lex.get_tokens(checklist.content)
    result = parse.get_form(tokens)
    context = {
        'checklist': checklist,
        'result': result
    }
    return render(request, 'view_checklist.html', context)

def checklist_comments(request, id):
    checklist = Checklist.objects.get(id=id)
    context = { 'checklist': checklist }
    return render(request, 'checklist_comments.html', context)

def edit_checklist(request, id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    checklist = Checklist.objects.get(id=id)
    if not checklist.owner == request.user:
        return HttpResponseRedirect('/')
    context = {}
    if request.method == 'POST':

		form = ChecklistForm(request.POST, instance=checklist)
		if 'Save' in request.POST:
			if form.is_valid():
				form.save()
                messages.add_message(request, messages.INFO, "Your changes have been saved...")
                return HttpResponseRedirect(reverse('view_checklist', args=[checklist.id]))
		if 'Preview' in request.POST:
			if form.is_valid():
				content = form.cleaned_data['content']
				tokens = lex.get_tokens(content)
				result = parse.get_form(tokens)
				context = {
					'checklist': checklist,
					'result': result
				}
				return render(request, 'view_checklist.html', context)
    else:
        form = ChecklistForm(instance=checklist)
    context['action'] = '/checklist/%s/edit' % id
    context['form'] = form
    return render(request, 'user/edit_checklist.html', context)

def clone_checklist(request, id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    old = Checklist.objects.get(id=id)
    checklist = Checklist.objects.create(
        title=old.title,
        content=old.content,
        owner=request.user,
    )
    form = ChecklistForm(instance=checklist)
    context = {}
    context['action'] = '/checklist/%s/edit' % checklist.id
    context['form'] = form
    messages.add_message(request, messages.INFO, "You have copied this checklist. Edit your version below.")
    return render(request, 'user/edit_checklist.html', context)

def delete_checklist(request, id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    checklist = Checklist.objects.get(id=id)
    if not checklist.owner == request.user:
        return HttpResponseRedirect('/')
    messages.add_message(request, messages.INFO, "You have deleted checklist %s." % checklist.title)
    checklist.delete()
    return HttpResponseRedirect('/')

def search(request):
    query = request.REQUEST["query"]
    tags = [t.strip() for t in query.split(",")]
    tagged_checklists = Checklist.objects.filter(tags__name__in=tags).distinct()
    matched_checklists = Checklist.objects.filter(title__icontains=query.strip())
    checklists = [checklist for checklist in tagged_checklists]
    checklists.extend([checklist for checklist in matched_checklists])
    context = { 'checklists': checklists, 'tags': ', '.join(tags) }
    return render(request, 'search_checklist.html', context)

def print_checklist(request, id):
    checklist = Checklist.objects.get(id=id)
    modified = checklist.modified
    tokens = lex.get_tokens(checklist.content)
    result = parse.get_form(tokens)
    context = {
        'checklist': checklist,
        'result': result,
        'modified': modified,
        'username': checklist.owner.username
    }
    return render(request, 'print_checklist.html', context)

@csrf_exempt
def preview_checklist(request):
    """
    Takes a request from the markitup editor and returns a preview.
    """
    result = ''
    if request.method == 'POST':
        if 'data' in request.POST:
            raw_data = request.POST['data']
            tokens = lex.get_tokens(raw_data)
            result = parse.get_form(tokens)
    return render(request, 'preview.html', {'content': result})

checklisthq/main/templates/user/checklist_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  {% if is_own_checklists %}
  <h1>Hello {{ user.username }}!</h1>
  <hr/>
  <h2>My Library</h2>
  {% else %}
  <h1>{{owner.username}}'s Library</h1>
  {% endif %}
  {% if checklists %}
  {% include '_checklists.html' %}
  {% else %}
  <hr/>
  {% if user.id == owner.id %}
  <p>You don't appear to have any checklists. Why not click on the
  "Create New Checklist" button below and get started? Alternatively,
  find someone else's, copy it to your library and modify it to your
  needs.</p>
  {% else %}
  <h2>Oh dear!</h2>
  <p>It appears that {{owner.username}} has not created any checklists.</p>
  {% endif %}
  <hr/>
  {% endif %}
  <a href="/browse" class="btn btn-primary">Browse all checklists</a>
  {% if user.is_authenticated %}
  <a href="/checklist/new" class="btn btn-success"> Create New Checklist </a>
  {% endif %}
</div>
{% endblock %}

checklisthq/main/templates/user/edit_checklist.html
{% extends 'base.html' %}
{% block css_includes %}
        <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/editor.css"/>
{% endblock %}
{% block content %}
<div class="container">
    <h1>Checklist Editor</h1>
    <hr/>
    <div class="row">
        <div class="span7">
            {% if saved %}
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <h4 class="alert-heading">Success!</h4>
                <p>{{saved}}</p>
            </div>
            {% endif %}
            <form action="{{ action }}" method="post" id="checklistform">
            {{ form.non_field_errors }}
            <strong>{{ form.title.label }}:</strong>
            {{ form.title }}<br/>
            <strong>{{ form.description.label }}:</strong>
            {{ form.description }}<br/>
            {{ form.content }}<br/>
            <strong>{{ form.tags.label }}:</strong>
            {{ form.tags }}
            {{ form.tags.description }}<br/>
            {% csrf_token %}
            <div class="btn-group">
              <input type="submit" id="Save" name="Save" Value="Save" class="btn btn-success"/>
              <input type="reset" value="Reset" class="btn btn-danger"/>
            </div>
            </form>
        </div>
        <div class="well span4">
            <h3>Help</h3>
            <p>Type a checklist into the box on the left. You can specify
            different parts of the checklist by clicking the buttons at the
            top of the text area.</p>
            <dl>
                <dt>== Heading ==</dt>
                <dd>Enclose headings in equals characters.</dt>
                <dt>[] Item</dt>
                <dd>Single items start with empty square brackets.</dd>
                <dt>() Choice Item</dt>
                <dd>Only one item from a group of choice items can be selected.</dd>
                <dt>[...] Text item</dt>
                <dd>Items that allow for textual entry start with [...].</dd>
                <dt>---</dt>
                <dd>Three or more minus characters create a horizontal line.</dd>
                <dt>Plain text</dt>
                <dd>Any other text is rendered as a paragraph.</dd>
            </dl>
        </div>
    </div>
</div>
{% endblock %}

{% block js_includes %}
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.markitup.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/editor.js"></script>
{% endblock %}

{% block jq_ready %}
$('#id_content').markItUp(editorSettings);
{% endblock %}